config/routes.rb
Rails.application.routes.draw do
  get 'game/start'

  get 'game/next'

  get 'game/benchmark'

  put 'game/put_user_input'

  get 'game/get_partial'

end

app/models/cell.rb
class Cell < ActiveRecord::Base
  belongs_to :grid
  validates :m, :n, :presence => true

end

app/models/grid.rb
class Grid < ActiveRecord::Base
  has_many :cells

  def duplicate_with_associations
    new_grid = self.dup
    new_grid.save
    self.cells.each do |cell|
      new_grid.cells << cell.dup
    end
    return new_grid
  end

end

app/models/hash_grid.rb
class HashGrid < ActiveRecord::Base
  serialize :cells
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  require 'benchmark'

  $m = 35
  $n = 45
  def start

    @grid_hash = HashGrid.new(:name => "smultron")
    # @grid_hash = HashGrid.where(name: 'smultron').last
    @grid_hash.cells = Hash.new

    $m.times { |i|
      $n.times { |j|
        if rand(8) == 1
          @grid_hash.cells[i.to_s + " " + j.to_s] = 1
        else
          @grid_hash.cells[i.to_s + " " + j.to_s] = 0
        end
      }
    }
    @grid_hash.save
  end

  def next

  end

  def benchmark

  end

  def put_user_input
    @grid_hash = HashGrid.where(name: 'smultron').last
    temp_hash = Hash.new
    temp_hash = params[:game]
    temp_hash.each do |key, value|
      @grid_hash.cells[key] = temp_hash[key]
    end
    @grid_hash.save
  end

  def get_partial
    @grid_hash = HashGrid.where(name: 'smultron').last
    temp_hash = @grid_hash.cells.dup

    $m.times { |i|
      $n.times { |j|

        neighbours_alive = 0

        start_pos_i = i - 1 < 0 ? i : i-1
        start_pos_j = j - 1 < 0 ? j : j-1
        end_pos_i = i + 1 >= $m ? i : i+1
        end_pos_j = j + 1 >= $n ? j : j+1

        for row_num in start_pos_i..end_pos_i
          for col_num in start_pos_j..end_pos_j
            if @grid_hash.cells[row_num.to_s + " " + col_num.to_s] == 1
              neighbours_alive += 1
            end
          end
        end

        if  @grid_hash.cells[i.to_s + " " + j.to_s] == 1
          neighbours_alive -= 1
          #under and over-population
          if neighbours_alive < 2 || neighbours_alive > 3
            temp_hash[i.to_s + " " + j.to_s] = 0
          end
        else
          #Reproduction
          if neighbours_alive == 3
            temp_hash[i.to_s + " " + j.to_s] = 1
          end
        end
      }
    }
    @grid_hash.cells = temp_hash.dup
    @grid_hash.save

    render :partial => 'grid.html.erb'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/_grid.html.erb
<%= content_tag :div, class: "grid_information", data: {m: $m, n: $n, gh: @grid_hash.cells} do %>
<% end %>

app/views/game/start.html.erb
<a href="#" id="take-a-step-button">Save grid and take a step</a>
<br>
<a href="#" id="start-cycle-button">Start cycle</a>
<br>
<a href="#" id="stop-cycle-button">Stop cycle</a>
<br>
<a href="#" id="save-button">save grid</a>
<br>
<a href="#" id="step-button">take a step without saving</a>
<br>
<%= link_to "Start over", game_start_path %>
<br>
<div id="grid-container">
    <%= render partial: "grid.html.erb"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameOfLife</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>